# PostgREST Configuration
db-uri = "postgres://api_gateway:api_gateway_secret@db:5432/whatsapp_gateway"
db-schema = "public"
db-anon-role = "api_gateway"
db-pool = 10
server-port = 3000
server-host = "0.0.0.0"

# Security
jwt-secret = "change-this-to-a-secure-random-string-min-32-chars"
# app.settings.jwt_secret = "change-this-to-a-secure-random-string-min-32-chars"

# CORS
cors-origin = "*"

# OpenAPI docs
openapi-mode = "follow-privileges"
